# Generated by Django 2.0.2 on 2018-12-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181205_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_posted',
            new_name='date_joined',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AddField(
            model_name='profile',
            name='Publisher',
            field=models.BooleanField(default=True),
        ),
    ]
