# Generated by Django 2.0.2 on 2018-12-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181205_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Publisher',
        ),
        migrations.AddField(
            model_name='profile',
            name='publisher',
            field=models.BooleanField(default=False),
        ),
    ]
